import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ConvexClientProvider from "@/components/ConvexProviderComponent";
import AuthGuard from "@/components/AuthGuard";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Would You Rather by Justin Storm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute={'class'}
          defaultTheme="system"
          enableSystem
        >
          <ConvexClientProvider>
            <AuthGuard>
              {children}
            </AuthGuard>
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
